server:
  port: ${PORT:3000}

spring:
  profiles:
    # Change this to 'prod' or remove it to stop forcing the 'dev' profile
    active: prod
  application:
    name: inventory-management-system

  # Bypass Security for now to ensure the database connects first
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

  datasource:
    # Use the Neon URL you provided earlier
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-fragrant-sound-aicvtx0b-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_c3NIOqXZPLp4}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # MUST be PostgreSQLDialect for Neon
        dialect: org.hibernate.dialect.PostgreSQLDialect

smb:
  server:
    ip: "172.29.80.1"
  share:
    name: "SunriseImages"
  username: "Rohit Prabhakar"
  password: "Flamekaiser@14"
  domain: ""