server:
  port: ${PORT:3000}  # Defaults to 3000, can be overridden

spring:
  profiles:
    active: dev
  application:
    name: inventory-management-system
  security:
    oauth2:
      resourceserver:
        jwt:
          # Variable: KEYCLOAK_ISSUER_URI
          # No default value -> Forces you to set it in Env/GitLab
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}

  datasource:
    # Variable: DB_HOST (Defaults to localhost if not set)
    # Variable: DB_NAME (Defaults to SunriseIGZ)
    url: jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=${DB_NAME:SunriseIGZ};encrypt=true;trustServerCertificate=true;

    # Variable: DB_USERNAME (Defaults to sa)
    username: ${DB_USERNAME:sa}

    # CRITICAL: DB_PASSWORD (No default value = Secure)
    # The app will fail to start if you don't provide this, which is good.
    password: ${DB_PASSWORD}

    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO

smb:
  server:
    ip: "172.29.80.1"
  share:
    name: "SunriseImages"
  username: "Rohit Prabhakar"
  password: "Flamekaiser@14"
  domain: ""